// ===== BANCOS LÉXICOS EXPANDIDOS PARA 60K =====
export const bancosLexic = {
  verbFisic: [
    "córrer", "escapar", "llançar-se", "saltar", "girar-se", "agafar", "empènyer", "arrossegar", 
    "tremolar", "caminar", "trontollar", "estirar-se", "agenollar-se", "alçar-se", "copar", 
    "tancar", "obrir", "trencar", "esquivar", "fugir", "envestir", "amagar-se", "recular", 
    "avançar", "precipitar-se", "atravesar", "enfilar", "deslitzar", "trepitjar", "ensopegar",
    "lliscar", "coure", "estirar", "empenyorar", "balancejar", "sacsejar", "moure", "desplaçar",
    "apropar", "allunyar", "envoltar", "creuar", "penetrar", "sortir", "entrar", "pujar", "baixar",
    "arribar", "marxar", "tornar", "quedar", "esperar", "observar", "buscar", "trobar", "perdre",
    "amagar", "descobrir", "revelar", "ocultar", "mostrar"
  ],
  verbVerbal: [
    "cridar", "xiuxiuejar", "murmura", "confessar", "preguntar", "respondre", "insistir", "suplicar",
    "admetre", "negar", "amenaçar", "prometre", "ordenar", "pregar", "explicar", "contar", "dir",
    "repetir", "aclarir", "confondre", "convèncer", "dissuadir", "alertar", "avisar", "advertir",
    "recordar", "oblidar", "suggerir", "proposar", "oferir", "exigir", "reclamar", "demanar",
    "agradecer", "excusar", "justificar", "aclarir", "desmentir", "confirmar"
  ],
  emocio: [
    "amb ràbia", "en silenci", "amb por", "amb esperança", "sense pensar-ho", "amb determinació",
    "amb dubte", "amb pressa", "lentament", "amb força", "amb tristesa", "amb coratge", "amb sarcasme",
    "amb tendresa", "amb fredor", "amb neguit", "amb resignació", "amb fúria", "amb calma",
    "amb desesperació", "amb ironia", "amb cautela", "amb ànsia", "amb sospita", "amb sorpresa",
    "amb confusió", "amb incredulitat", "amb alleujament", "amb desànim", "amb il·lusió", "amb rancor",
    "amb pietat", "amb orgull", "amb vergonya", "amb curiositat", "amb impaciència", "amb prudència",
    "amb temeritat", "amb dol", "amb ràbia continguda", "amb esperança trencada"
  ],
  adverbis: [
    "de cop", "lentament", "ràpid", "en silenci", "amb força", "sense fer soroll", "de sobte",
    "poc a poc", "bruscament", "suavament", "inesperadament", "constantment", "amb cura", "amb nervis",
    "amb pressa", "amb calma", "amb precaució", "amb valentia", "amb temeritat", "amb prudència",
    "amb desconfiança", "amb seguretat", "amb incertesa", "amb decisió", "amb vacil·lació",
    "amb fermesa", "amb suavitat", "amb duresa", "amb delicadesa", "amb violència", "amb ternura",
    "amb fredor", "amb calidesa", "amb intensitat", "amb lleugeresa", "amb pesantor"
  ],
  connectors: [
    "Mentrestant,", "Al cap d’uns minuts,", "De cop i volta,", "Sense adonar-se,", "Més tard,",
    "Llavors,", "Però,", "No obstant això,", "Aleshores,", "Després de tot,", "En aquell instant,",
    "Paradoxalment,", "Curiosament,", "Sorprenentment,", "Inevitablement,", "Finalment,", "A poc a poc,",
    "De sobte,", "Mentre tant,", "Tanmateix,", "Malgrat tot,", "Així doncs,", "Per això,", "Conseqüentment,",
    "No obstant,", "A més,", "D'altra banda,", "En realitat,", "De fet,", "En el fons,"
  ],
  pensament: [
    "{p0} va pensar que tot era un error.",
    "No podia creure el que veia.",
    "Havia de prendre una decisió, i ràpid.",
    "Si fallava, no hi hauria segona oportunitat.",
    "Tot depenia d’aquell moment.",
    "{p0} es preguntava si havia estat un error.",
    "La ment de {p0} corria més ràpid que les seves cames.",
    "No hi havia temps per dubtar.",
    "{p0} sabia que això canviaria tot.",
    "No podia permetre’s fallar ara.",
    "Era massa tard per tornar enrere.",
    "{p0} sentia que algú l’observava.",
    "Aquella idea no el deixava en pau.",
    "Havia subestimat el perill.",
    "No podia confiar en ningú.",
    "{p0} es preguntava quant temps més aguantaria.",
    "Aquella era la seva última oportunitat.",
    "No hi havia marxa enrere.",
    "{p0} sabia que s’estava jugant la vida.",
    "Aquella decisió ho canviaria tot."
  ]
};

// ===== PLANTILLES EXPANDIDES - 60+ PER TIPUS =====
export const plantillesCombinades = {
  obertura: [
    "La llum entrava quan {p0} va obrir els ulls.",
    "{p0} no sabia que aquell dia {p1} canviaria tot.",
    "{p0} mirava {esc} pensant en {p2}.",
    "El rellotge marcava les {hora} quan {p0} va prendre la decisió.",
    "El silenci pesava sobre {esc} mentre {p0} respirava fons.",
    "{p0} va sentir un calfred en creuar la porta de {esc}.",
    "Aquell matí, {p0} va despertar amb la sensació que algo anava malament.",
    "Els ulls de {p0} es van clavar en {esc} buscant una resposta.",
    "El soroll el va treure del seu pensament.",
    "Una ombra es va moure al fons de {esc}.",
    "{p0} no esperava trobar-se allò.",
    "El vent va colpejar la finestra de {esc}.",
    "El telèfon va sonar trencant el silenci de {esc}.",
    "{p0} va notar que algo havia canviat a {esc}.",
    "La porta de {esc} estava entreoberta.",
    "Una olor estranya impregnava {esc}.",
    "{p0} va trobar una nota sobre la taula de {esc}.",
    "Els passos ressonaven a {esc}.",
    "{p0} va sentir una veu procedent de {esc}.",
    "La llum de {esc} parpellejava.",
    "Algo brillava al fons de {esc}.",
    "{p0} va veure una figura a {esc}.",
    "El terra de {esc} estava humit.",
    "Una porta es va tancar de cop a {esc}.",
    "{p0} va notar una presència a {esc}.",
    "El mirall de {esc} reflectia algo estrany.",
    "{p0} va trobar una porta que abans no hi era.",
    "Les ombres a {esc} es movien soles.",
    "{p0} va sentir un murmuri procedent de {esc}.",
    "Algo s’havia mogut a {esc}.",
    "La temperatura de {esc} havia baixat.",
    "{p0} va veure el seu reflex distorsionat a {esc}.",
    "Una corriola va passar per {esc}.",
    "{p0} va trobar un objecte estrany a {esc}.",
    "Les parets de {esc} semblaven més properes.",
    "{p0} va sentir un pes a la pit en entrar a {esc}.",
    "El rellotge de {esc} s’havia parat a les {hora}.",
    "{p0} va notar que algú havia estat allà.",
    "Les petjades a {esc} no eren les seves.",
    "Algo havia caigut a {esc}.",
    "{p0} va veure una porta tancada a {esc}.",
    "El silenci de {esc} era inquietant.",
    "{p0} va trobar una marca a la paret de {esc}.",
    "Les finestres de {esc} estaven totes tancades.",
    "{p0} va sentir un cop sec procedent de {esc}.",
    "Algo s’estava cremant a {esc}.",
    "{p0} va notar un gust metàl·lic a la boca.",
    "Les ombres de {esc} formaven una figura.",
    "{p0} va trobar una clau a {esc}.",
    "La porta de {esc} gemegava.",
    "{p0} va veure un moviment pel rabillo de l’ull.",
    "Algo brillava sota {esc}.",
    "{p0} va sentir la seva pròpia respiració a {esc}.",
    "Les parets de {esc} suaven.",
    "{p0} va trobar una fotografia antiga a {esc}.",
    "El terra de {esc} estava fred.",
    "{p0} va notar que el temps s’havia aturat a {esc}.",
    "Algo s’estava desfent a {esc}."
  ],
  accio: [
    "{p0} va {verbfisic} {emocio} cap a {esc}.",
    "Sense pensar-ho, {p0} va {verbfisic} per {mon}.",
    "{p0} va {verbfisic} {adverbi} mentre {p1} mirava.",
    "{p0} va {verbfisic} {emocio} i després es va aturar.",
    "{p0} va avançar {adverbi} cap a la foscor de {esc}.",
    "Amb un moviment brusc, {p0} va {verbfisic} {emocio}.",
    "{p0} no va dubtar: va {verbfisic} {adverbi} i va creuar {esc}.",
    "El cos de {p0} va reaccionar abans que la ment: va {verbfisic} {emocio}.",
    "{p0} va {verbfisic} {adverbi} i va sentir un calfred.",
    "La respiració de {p0} es va accelerar mentre {verbfisic} {emocio}.",
    "{p0} va {verbfisic} {adverbi} cap a la sortida.",
    "Sense mirar enrere, {p0} va {verbfisic} {emocio}.",
    "{p0} va {verbfisic} {adverbi} i va ensopegar.",
    "El cor de {p0} bategava fort mentre {verbfisic} {emocio}.",
    "{p0} va {verbfisic} {adverbi} i va sentir un dolor.",
    "Amb determinació, {p0} va {verbfisic} {emocio}.",
    "{p0} va {verbfisic} {adverbi} i va mirar al voltant.",
    "La por va fer que {p0} {verbfisic} {emocio}.",
    "{p0} va {verbfisic} {adverbi} i va agafar aire.",
    "Sense fer soroll, {p0} va {verbfisic} {emocio}.",
    "{p0} va {verbfisic} {adverbi} i va trobar una porta.",
    "La urgència va empènyer {p0} a {verbfisic} {emocio}.",
    "{p0} va {verbfisic} {adverbi} i va sentir un cop.",
    "Amb precaució, {p0} va {verbfisic} {emocio}.",
    "{p0} va {verbfisic} {adverbi} i va descobrir algo.",
    "La desesperació va fer que {p0} {verbfisic} {emocio}.",
    "{p0} va {verbfisic} {adverbi} i va cridar.",
    "Amb ràbia, {p0} va {verbfisic} {emocio}.",
    "{p0} va {verbfisic} {adverbi} i va caure.",
    "La sorpresa va fer que {p0} {verbfisic} {emocio}.",
    "{p0} va {verbfisic} {adverbi} i va trobar una pista.",
    "Amb tristesa, {p0} va {verbfisic} {emocio}.",
    "{p0} va {verbfisic} {adverbi} i va sentir una veu.",
    "La curiositat va empènyer {p0} a {verbfisic} {emocio}.",
    "{p0} va {verbfisic} {adverbi} i va obrir una porta.",
    "Amb por, {p0} va {verbfisic} {emocio}.",
    "{p0} va {verbfisic} {adverbi} i va veure una llum.",
    "La determinació va fer que {p0} {verbfisic} {emocio}.",
    "{p0} va {verbfisic} {adverbi} i va trobar una sortida.",
    "Amb esperança, {p0} va {verbfisic} {emocio}.",
    "{p0} va {verbfisic} {adverbi} i va sentir un murmuri.",
    "La ira va fer que {p0} {verbfisic} {emocio}.",
    "{p0} va {verbfisic} {adverbi} i va agafar algo.",
    "Amb cautela, {p0} va {verbfisic} {emocio}.",
    "{p0} va {verbfisic} {adverbi} i va descobrir una habitació.",
    "La pressa va fer que {p0} {verbfisic} {emocio}.",
    "{p0} va {verbfisic} {adverbi} i va sentir un soroll.",
    "Amb valentia, {p0} va {verbfisic} {emocio}.",
    "{p0} va {verbfisic} {adverbi} i va trobar una escala.",
    "La confusió va fer que {p0} {verbfisic} {emocio}.",
    "{p0} va {verbfisic} {adverbi} i va veure una ombra.",
    "Amb calma, {p0} va {verbfisic} {emocio}.",
    "{p0} va {verbfisic} {adverbi} i va obrir una finestra.",
    "La sorpresa va fer que {p0} {verbfisic} {emocio}.",
    "{p0} va {verbfisic} {adverbi} i va trobar una nota.",
    "Amb determinació, {p0} va {verbfisic} {emocio}.",
    "{p0} va {verbfisic} {adverbi} i va sentir passos.",
    "La por va fer que {p0} {verbfisic} {emocio}.",
    "{p0} va {verbfisic} {adverbi} i va descobrir un passadís."
  ],
  dialog: [
    '"No puc més", va {verbverbal} {p0}.',
    '"Tens raó", va respondre {p1}. "Però ho hem de provar."',
    '"Què vols dir?", va preguntar {p0}.',
    '"Que tot ha canviat", va xiuxiuejar {p2}.',
    '"No t’ho crec", va tallar {p1}.',
    '"Mira això", va dir {p0} assenyalant {esc}.',
    '"No tenim temps", va insistir {p1} amb urgència.',
    '"Confia en mi", va suplicar {p2} baixant la veu.',
    '"Això és un error", va murmurar {p0}.',
    '"No hi ha una altra sortida", va admetre {p1}.',
    '"Només confia", va ordenar {p2}.',
    '"No pensava que arribéssim tan lluny", va confessar {p0}.',
    '"Estàs segur?", va preguntar {p1} amb dubte.',
    '"No tenim una altra opció", va respondre {p2}.',
    '"Això no té sentit", va exclamar {p0}.',
    '"Només segueix-me", va dir {p1}.',
    '"No puc fer-ho sola", va admetre {p2}.',
    '"Confia en el teu instint", va suggerir {p0}.',
    '"Això és una trampa", va alertar {p1}.',
    '"No hi ha temps per discutir", va tallar {p2}.',
    '"M’estàs amagant algo", va acusar {p0}.',
    '"No és el que sembla", va justificar {p1}.',
    '"Només vull ajudar", va explicar {p2}.',
    '"Això és massa perillós", va advertir {p0}.',
    '"No tinguis por", va calmar {p1}.',
    '"No puc perdre’t ara", va confessar {p2}.',
    '"Això ho canvia tot", va dir {p0}.',
    '"Només fes el que et dic", va ordenar {p1}.',
    '"No em deixis sola", va suplicar {p2}.',
    '"Això no és just", va protestar {p0}.',
    '"Només queda una oportunitat", va recordar {p1}.',
    '"No sé què fer", va admetre {p2}.',
    '"Això és la nostra única sortida", va proposar {p0}.',
    '"No t’ho puc explicar ara", va respondre {p1}.',
    '"Només confia en mi", va repetir {p2}.',
    '"Això és impossible", va exclamar {p0}.',
    '"Només queda provar-ho", va insistir {p1}.',
    '"No puc més", va confessar {p2}.',
    '"Això ho arreglarà tot", va prometre {p0}.',
    '"No és tan fàcil", va respondre {p1}.',
    '"Només necessito un minut", va demanar {p2}.',
    '"Això és el final", va dir {p0} baixant la veu.',
    '"No estàs sola", va assegurar {p1}.',
    '"Només vull que estiguis bé", va confessar {p2}.',
    '"Això és el que hem d’afrontar", va dir {p0}.',
    '"No tinguis dubtes", va animar {p1}.',
    '"Només queda creure", va suplicar {p2}.',
    '"Això ho canvia tot", va repetir {p0}.',
    '"No em deixis ara", va demanar {p1}.',
    '"Només vull que ho entenguis", va explicar {p2}.',
    '"Això és el nostre destí", va dir {p0}.',
    '"No tinguis por del que vindrà", va calmar {p1}.',
    '"Només queda lluitar", va ordenar {p2}.',
    '"Això és el que hem buscat", va confessar {p0}.',
    '"No estàs preparada", va advertir {p1}.',
    '"Només vull protegir-te", va respondre {p2}.',
    '"Això és el nostre moment", va dir {p0}.',
    '"No tinguis dubtes ara", va insistir {p1}.'
  ],
  descripcio: [
    "L’aire a {esc} olia a pluja.",
    "{mon} s’estenia davant d’ells, infinit.",
    "Les parets de {esc} guardaven secrets.",
    "El vent bufava {adverbi} des de {mon}.",
    "L’ombra de {esc} s’allargava sobre el terra fred.",
    "Un silenci dens omplia cada racó de {mon}.",
    "La llum jugava amb les textures de {esc}, creant patrons impossibles.",
    "{mon} semblava viure amb vida pròpia, respirant al seu ritme.",
    "El terra de {esc} cruixia sota els seus peus.",
    "Una olor metàl·lica flotava a {mon}.",
    "Les parets de {esc} estaven plenes de marques.",
    "El fred de {mon} se li va clavar als ossos.",
    "La pols ballava a l’aire de {esc}.",
    "Un eco ressonava per {mon}.",
    "Les finestres de {esc} estaven emboirades.",
    "El silenci de {mon} era ensordidor.",
    "Les parets de {esc} suaven humitat.",
    "Una llum tènue il·luminava {esc}.",
    "El terra de {mon} estava ple de rastres.",
    "Les ombres de {esc} ballaven a la paret.",
    "Un fred intens sortia de {mon}.",
    "Les parets de {esc} semblaven respirar.",
    "El sostre de {esc} estava ple d’esquerdes.",
    "Una corrent d’aire passava per {mon}.",
    "Les portes de {esc} gemegaven.",
    "El terra de {mon} estava irregular.",
    "Les parets de {esc} tenien taques fosques.",
    "Una olor a vell impregnava {esc}.",
    "El silenci de {mon} pesava.",
    "Les finestres de {esc} estaven trencades.",
    "El terra de {mon} cruixia.",
    "Les parets de {esc} semblaven moure’s.",
    "Una foscor espessa omplia {esc}.",
    "El sostre de {mon} estava baix.",
    "Les portes de {esc} estaven tancades.",
    "El terra de {mon} estava humit.",
    "Les parets de {esc} tenien grafitis.",
    "Una olor a podriment sortia de {esc}.",
    "El silenci de {mon} era absolut.",
    "Les finestres de {esc} estaven tapades.",
    "El terra de {mon} estava ple de runes.",
    "Les parets de {esc} semblaven més properes.",
    "Una llum vermella il·luminava {esc}.",
    "El sostre de {mon} estava enrunat.",
    "Les portes de {esc} estaven bloquejades.",
    "El terra de {mon} estava ple de pols.",
    "Les parets de {esc} tenien marques de mans.",
    "Una olor a fum sortia de {esc}.",
    "El silenci de {mon} era inquietant.",
    "Les finestres de {esc} estaven trencades.",
    "El terra de {mon} estava irregular.",
    "Les parets de {esc} semblaven suar.",
    "Una foscor densa omplia {esc}.",
    "El sostre de {mon} estava ple de teranyines.",
    "Les portes de {esc} gemegaven al obrir-se.",
    "El terra de {mon} estava fred.",
    "Les parets de {esc} tenien inscripcions.",
    "Una olor a ferro sortia de {esc}.",
    "El silenci de {mon} era tens."
  ],
  cliffhanger: [
    "Però llavors, va sentir un soroll.",
    "I en aquell moment, tot va canviar.",
    "No tenia ni idea del que venia després.",
    "El telèfon va sonar.",
    "La porta es va obrir sola.",
    "Algú els observava des de l’ombra.",
    "El terra va tremolar sota els seus peus.",
    "Una figura va aparèixer al final del passadís.",
    "El llum es va apagar.",
    "Va trobar una nota a terra.",
    "El motor va fallar.",
    "Alguna cosa es movia dins {esc}.",
    "Un crit va trencar el silenci.",
    "La porta es va tancar de cop.",
    "Va veure una ombra moure’s.",
    "El terra va cedir sota els seus peus.",
    "Algú va xiuxiuejar el seu nom.",
    "La llum va parpellejar.",
    "Va sentir passos darrere seu.",
    "La paret es va obrir.",
    "El rellotge es va parar.",
    "Va trobar una porta secreta.",
    "El terra estava ple de petjades.",
    "Algú havia estat allà.",
    "La finestra es va trencar.",
    "Va sentir la seva pròpia respiració.",
    "El mirall va reflectir algo estrany.",
    "La porta gemegava.",
    "Va veure una llum al final.",
    "El terra estava humit.",
    "Algú va tocar la seva espatlla.",
    "El sostre va cruixir.",
    "Va trobar una clau.",
    "La foscor es va fer més densa.",
    "Va sentir un murmuri.",
    "La paret tenia una marca.",
    "El terra estava fred.",
    "Algú va apagar la llum.",
    "Va veure una figura a la finestra.",
    "El terra va vibrar.",
    "Va trobar una fotografia.",
    "La porta estava bloquejada.",
    "Va sentir un cop sec.",
    "El mirall es va trencar.",
    "Va veure una ombra al sostre.",
    "El terra estava ple de runes.",
    "Algú va cridar el seu nom.",
    "La llum es va fer vermella.",
    "Va trobar una escala.",
    "El terra va cedir.",
    "Va sentir passos que s’acostaven.",
    "La porta es va obrir lentament.",
    "Va veure una figura al fons.",
    "El terra estava ple de pols.",
    "Algú va xiuxiuejar darrere seu.",
    "La llum va parpellejar tres cops.",
    "Va trobar una nota amb el seu nom.",
    "El terra va tremolar fort.",
    "Va sentir la porta tancar-se."
  ],
  tancamentCapitol: [
    "El capítol acabava aquí.",
    "Demà tornaria al mateix lloc.",
    "La decisió estava presa.",
    "No hi havia volta enrere.",
    "Aquella nit canviaria tot.",
    "El destí ja estava marcat.",
    "No quedava temps per lamentar-se.",
    "El següent pas seria l’últim.",
    "Res tornaria a ser igual.",
    "El compte enrere havia començat.",
    "La veritat sortiria a la llum.",
    "No quedava una altra opció.",
    "El final s’acostava.",
    "Tot estava a punt de canviar.",
    "La línia s’havia creuat.",
    "No quedava marxa enrere.",
    "El moment havia arribat.",
    "Tot depenia d’ell.",
    "La jugada estava feta.",
    "El secret sortiria.",
    "No quedava temps.",
    "El destí s’havia complert.",
    "La porta s’havia obert.",
    "No hi havia una altra sortida.",
    "El cercle s’havia tancat.",
    "Tot estava en marxa.",
    "No quedava una altra possibilitat.",
    "El final s’acostava ràpid.",
    "La decisió era irrevocable.",
    "Tot estava escrit."
  ]
};
